defmodule GitHubEx.Codegen.AtomRegistry do
  @moduledoc false

  @methods %{
    "delete" => :delete,
    "get" => :get,
    "head" => :head,
    "options" => :options,
    "patch" => :patch,
    "post" => :post,
    "put" => :put
  }

  @modules %{
    "GitHubEx.Actions" => GitHubEx.Actions,
    "GitHubEx.Activity" => GitHubEx.Activity,
    "GitHubEx.Apps" => GitHubEx.Apps,
    "GitHubEx.Billing" => GitHubEx.Billing,
    "GitHubEx.Campaigns" => GitHubEx.Campaigns,
    "GitHubEx.Checks" => GitHubEx.Checks,
    "GitHubEx.Classroom" => GitHubEx.Classroom,
    "GitHubEx.CodeScanning" => GitHubEx.CodeScanning,
    "GitHubEx.CodeSecurity" => GitHubEx.CodeSecurity,
    "GitHubEx.CodesOfConduct" => GitHubEx.CodesOfConduct,
    "GitHubEx.Codespaces" => GitHubEx.Codespaces,
    "GitHubEx.Copilot" => GitHubEx.Copilot,
    "GitHubEx.Credentials" => GitHubEx.Credentials,
    "GitHubEx.Dependabot" => GitHubEx.Dependabot,
    "GitHubEx.DependencyGraph" => GitHubEx.DependencyGraph,
    "GitHubEx.Emojis" => GitHubEx.Emojis,
    "GitHubEx.EnterpriseTeamMemberships" => GitHubEx.EnterpriseTeamMemberships,
    "GitHubEx.EnterpriseTeamOrganizations" => GitHubEx.EnterpriseTeamOrganizations,
    "GitHubEx.EnterpriseTeams" => GitHubEx.EnterpriseTeams,
    "GitHubEx.Gists" => GitHubEx.Gists,
    "GitHubEx.Git" => GitHubEx.Git,
    "GitHubEx.Gitignore" => GitHubEx.Gitignore,
    "GitHubEx.HostedCompute" => GitHubEx.HostedCompute,
    "GitHubEx.Interactions" => GitHubEx.Interactions,
    "GitHubEx.Issues" => GitHubEx.Issues,
    "GitHubEx.Licenses" => GitHubEx.Licenses,
    "GitHubEx.Markdown" => GitHubEx.Markdown,
    "GitHubEx.Meta" => GitHubEx.Meta,
    "GitHubEx.Migrations" => GitHubEx.Migrations,
    "GitHubEx.Oidc" => GitHubEx.Oidc,
    "GitHubEx.Orgs" => GitHubEx.Orgs,
    "GitHubEx.Packages" => GitHubEx.Packages,
    "GitHubEx.PrivateRegistries" => GitHubEx.PrivateRegistries,
    "GitHubEx.Projects" => GitHubEx.Projects,
    "GitHubEx.Pulls" => GitHubEx.Pulls,
    "GitHubEx.RateLimit" => GitHubEx.RateLimit,
    "GitHubEx.Reactions" => GitHubEx.Reactions,
    "GitHubEx.Repos" => GitHubEx.Repos,
    "GitHubEx.Search" => GitHubEx.Search,
    "GitHubEx.SecretScanning" => GitHubEx.SecretScanning,
    "GitHubEx.SecurityAdvisories" => GitHubEx.SecurityAdvisories,
    "GitHubEx.Teams" => GitHubEx.Teams,
    "GitHubEx.Users" => GitHubEx.Users
  }

  @module_names %{
    "Actions" => GitHubEx.Actions,
    "Activity" => GitHubEx.Activity,
    "Apps" => GitHubEx.Apps,
    "Billing" => GitHubEx.Billing,
    "Campaigns" => GitHubEx.Campaigns,
    "Checks" => GitHubEx.Checks,
    "Classroom" => GitHubEx.Classroom,
    "CodeScanning" => GitHubEx.CodeScanning,
    "CodeSecurity" => GitHubEx.CodeSecurity,
    "CodesOfConduct" => GitHubEx.CodesOfConduct,
    "Codespaces" => GitHubEx.Codespaces,
    "Copilot" => GitHubEx.Copilot,
    "Credentials" => GitHubEx.Credentials,
    "Dependabot" => GitHubEx.Dependabot,
    "DependencyGraph" => GitHubEx.DependencyGraph,
    "Emojis" => GitHubEx.Emojis,
    "EnterpriseTeamMemberships" => GitHubEx.EnterpriseTeamMemberships,
    "EnterpriseTeamOrganizations" => GitHubEx.EnterpriseTeamOrganizations,
    "EnterpriseTeams" => GitHubEx.EnterpriseTeams,
    "Gists" => GitHubEx.Gists,
    "Git" => GitHubEx.Git,
    "Gitignore" => GitHubEx.Gitignore,
    "HostedCompute" => GitHubEx.HostedCompute,
    "Interactions" => GitHubEx.Interactions,
    "Issues" => GitHubEx.Issues,
    "Licenses" => GitHubEx.Licenses,
    "Markdown" => GitHubEx.Markdown,
    "Meta" => GitHubEx.Meta,
    "Migrations" => GitHubEx.Migrations,
    "Oidc" => GitHubEx.Oidc,
    "Orgs" => GitHubEx.Orgs,
    "Packages" => GitHubEx.Packages,
    "PrivateRegistries" => GitHubEx.PrivateRegistries,
    "Projects" => GitHubEx.Projects,
    "Pulls" => GitHubEx.Pulls,
    "RateLimit" => GitHubEx.RateLimit,
    "Reactions" => GitHubEx.Reactions,
    "Repos" => GitHubEx.Repos,
    "Search" => GitHubEx.Search,
    "SecretScanning" => GitHubEx.SecretScanning,
    "SecurityAdvisories" => GitHubEx.SecurityAdvisories,
    "Teams" => GitHubEx.Teams,
    "Users" => GitHubEx.Users
  }

  @module_event_segments %{
    GitHubEx.Actions => :actions,
    GitHubEx.Activity => :activity,
    GitHubEx.Apps => :apps,
    GitHubEx.Billing => :billing,
    GitHubEx.Campaigns => :campaigns,
    GitHubEx.Checks => :checks,
    GitHubEx.Classroom => :classroom,
    GitHubEx.CodeScanning => :code_scanning,
    GitHubEx.CodeSecurity => :code_security,
    GitHubEx.CodesOfConduct => :codes_of_conduct,
    GitHubEx.Codespaces => :codespaces,
    GitHubEx.Copilot => :copilot,
    GitHubEx.Credentials => :credentials,
    GitHubEx.Dependabot => :dependabot,
    GitHubEx.DependencyGraph => :dependency_graph,
    GitHubEx.Emojis => :emojis,
    GitHubEx.EnterpriseTeamMemberships => :enterprise_team_memberships,
    GitHubEx.EnterpriseTeamOrganizations => :enterprise_team_organizations,
    GitHubEx.EnterpriseTeams => :enterprise_teams,
    GitHubEx.Gists => :gists,
    GitHubEx.Git => :git,
    GitHubEx.Gitignore => :gitignore,
    GitHubEx.HostedCompute => :hosted_compute,
    GitHubEx.Interactions => :interactions,
    GitHubEx.Issues => :issues,
    GitHubEx.Licenses => :licenses,
    GitHubEx.Markdown => :markdown,
    GitHubEx.Meta => :meta,
    GitHubEx.Migrations => :migrations,
    GitHubEx.Oidc => :oidc,
    GitHubEx.Orgs => :orgs,
    GitHubEx.Packages => :packages,
    GitHubEx.PrivateRegistries => :private_registries,
    GitHubEx.Projects => :projects,
    GitHubEx.Pulls => :pulls,
    GitHubEx.RateLimit => :rate_limit,
    GitHubEx.Reactions => :reactions,
    GitHubEx.Repos => :repos,
    GitHubEx.Search => :search,
    GitHubEx.SecretScanning => :secret_scanning,
    GitHubEx.SecurityAdvisories => :security_advisories,
    GitHubEx.Teams => :teams,
    GitHubEx.Users => :users
  }

  @functions %{
    "accept_invitation_for_authenticated_user" => :accept_invitation_for_authenticated_user,
    "add" => :add,
    "add_app_access_restrictions" => :add_app_access_restrictions,
    "add_assignees" => :add_assignees,
    "add_blocked_by_dependency" => :add_blocked_by_dependency,
    "add_collaborator" => :add_collaborator,
    "add_copilot_seats_for_teams" => :add_copilot_seats_for_teams,
    "add_copilot_seats_for_users" => :add_copilot_seats_for_users,
    "add_custom_labels_to_self_hosted_runner_for_org" =>
      :add_custom_labels_to_self_hosted_runner_for_org,
    "add_custom_labels_to_self_hosted_runner_for_repo" =>
      :add_custom_labels_to_self_hosted_runner_for_repo,
    "add_email_for_authenticated_user" => :add_email_for_authenticated_user,
    "add_field_for_org" => :add_field_for_org,
    "add_field_for_user" => :add_field_for_user,
    "add_issue_field_values" => :add_issue_field_values,
    "add_item_for_org" => :add_item_for_org,
    "add_item_for_user" => :add_item_for_user,
    "add_labels" => :add_labels,
    "add_member_legacy" => :add_member_legacy,
    "add_or_update_membership_for_user_in_org" => :add_or_update_membership_for_user_in_org,
    "add_or_update_membership_for_user_legacy" => :add_or_update_membership_for_user_legacy,
    "add_or_update_repo_permissions_in_org" => :add_or_update_repo_permissions_in_org,
    "add_or_update_repo_permissions_legacy" => :add_or_update_repo_permissions_legacy,
    "add_repo_access_to_self_hosted_runner_group_in_org" =>
      :add_repo_access_to_self_hosted_runner_group_in_org,
    "add_repo_to_installation_for_authenticated_user" =>
      :add_repo_to_installation_for_authenticated_user,
    "add_repository_for_secret_for_authenticated_user" =>
      :add_repository_for_secret_for_authenticated_user,
    "add_security_manager_team" => :add_security_manager_team,
    "add_selected_repo_to_org_secret" => :add_selected_repo_to_org_secret,
    "add_selected_repo_to_org_variable" => :add_selected_repo_to_org_variable,
    "add_self_hosted_runner_to_group_for_org" => :add_self_hosted_runner_to_group_for_org,
    "add_social_account_for_authenticated_user" => :add_social_account_for_authenticated_user,
    "add_status_check_contexts" => :add_status_check_contexts,
    "add_sub_issue" => :add_sub_issue,
    "add_team_access_restrictions" => :add_team_access_restrictions,
    "add_user_access_restrictions" => :add_user_access_restrictions,
    "approve_workflow_run" => :approve_workflow_run,
    "assign_team_to_org_role" => :assign_team_to_org_role,
    "assign_user_to_org_role" => :assign_user_to_org_role,
    "attach_configuration" => :attach_configuration,
    "attach_enterprise_configuration" => :attach_enterprise_configuration,
    "block" => :block,
    "block_user" => :block_user,
    "bulk_add" => :bulk_add,
    "bulk_remove" => :bulk_remove,
    "cancel_copilot_seat_assignment_for_teams" => :cancel_copilot_seat_assignment_for_teams,
    "cancel_copilot_seat_assignment_for_users" => :cancel_copilot_seat_assignment_for_users,
    "cancel_import" => :cancel_import,
    "cancel_invitation" => :cancel_invitation,
    "cancel_pages_deployment" => :cancel_pages_deployment,
    "cancel_workflow_run" => :cancel_workflow_run,
    "check_automated_security_fixes" => :check_automated_security_fixes,
    "check_blocked" => :check_blocked,
    "check_blocked_user" => :check_blocked_user,
    "check_collaborator" => :check_collaborator,
    "check_following_for_user" => :check_following_for_user,
    "check_if_merged" => :check_if_merged,
    "check_immutable_releases" => :check_immutable_releases,
    "check_is_starred" => :check_is_starred,
    "check_membership_for_user" => :check_membership_for_user,
    "check_permissions_for_devcontainer" => :check_permissions_for_devcontainer,
    "check_permissions_for_repo_in_org" => :check_permissions_for_repo_in_org,
    "check_permissions_for_repo_legacy" => :check_permissions_for_repo_legacy,
    "check_person_is_followed_by_authenticated" => :check_person_is_followed_by_authenticated,
    "check_private_vulnerability_reporting" => :check_private_vulnerability_reporting,
    "check_public_membership_for_user" => :check_public_membership_for_user,
    "check_repo_is_starred_by_authenticated_user" => :check_repo_is_starred_by_authenticated_user,
    "check_token" => :check_token,
    "check_user_can_be_assigned" => :check_user_can_be_assigned,
    "check_user_can_be_assigned_to_issue" => :check_user_can_be_assigned_to_issue,
    "check_vulnerability_alerts" => :check_vulnerability_alerts,
    "code" => :code,
    "codeowners_errors" => :codeowners_errors,
    "codespace_machines_for_authenticated_user" => :codespace_machines_for_authenticated_user,
    "commit_autofix" => :commit_autofix,
    "commits" => :commits,
    "compare_commits" => :compare_commits,
    "convert_member_to_outside_collaborator" => :convert_member_to_outside_collaborator,
    "copilot_content_exclusion_for_organization" => :copilot_content_exclusion_for_organization,
    "copilot_metrics_for_organization" => :copilot_metrics_for_organization,
    "copilot_metrics_for_team" => :copilot_metrics_for_team,
    "create" => :create,
    "create_artifact_deployment_record" => :create_artifact_deployment_record,
    "create_artifact_storage_record" => :create_artifact_storage_record,
    "create_attestation" => :create_attestation,
    "create_autofix" => :create_autofix,
    "create_autolink" => :create_autolink,
    "create_blob" => :create_blob,
    "create_campaign" => :create_campaign,
    "create_comment" => :create_comment,
    "create_commit" => :create_commit,
    "create_commit_comment" => :create_commit_comment,
    "create_commit_signature_protection" => :create_commit_signature_protection,
    "create_commit_status" => :create_commit_status,
    "create_configuration" => :create_configuration,
    "create_configuration_for_enterprise" => :create_configuration_for_enterprise,
    "create_deploy_key" => :create_deploy_key,
    "create_deployment" => :create_deployment,
    "create_deployment_branch_policy" => :create_deployment_branch_policy,
    "create_deployment_protection_rule" => :create_deployment_protection_rule,
    "create_deployment_status" => :create_deployment_status,
    "create_dispatch_event" => :create_dispatch_event,
    "create_draft_item_for_authenticated_user" => :create_draft_item_for_authenticated_user,
    "create_draft_item_for_org" => :create_draft_item_for_org,
    "create_environment_variable" => :create_environment_variable,
    "create_for_authenticated_user" => :create_for_authenticated_user,
    "create_for_commit_comment" => :create_for_commit_comment,
    "create_for_issue" => :create_for_issue,
    "create_for_issue_comment" => :create_for_issue_comment,
    "create_for_pull_request_review_comment" => :create_for_pull_request_review_comment,
    "create_for_release" => :create_for_release,
    "create_fork" => :create_fork,
    "create_from_manifest" => :create_from_manifest,
    "create_gpg_key_for_authenticated_user" => :create_gpg_key_for_authenticated_user,
    "create_hosted_runner_for_org" => :create_hosted_runner_for_org,
    "create_in_org" => :create_in_org,
    "create_installation_access_token" => :create_installation_access_token,
    "create_invitation" => :create_invitation,
    "create_issue_field" => :create_issue_field,
    "create_issue_type" => :create_issue_type,
    "create_label" => :create_label,
    "create_milestone" => :create_milestone,
    "create_network_configuration_for_org" => :create_network_configuration_for_org,
    "create_oidc_custom_property_inclusion_for_enterprise" =>
      :create_oidc_custom_property_inclusion_for_enterprise,
    "create_oidc_custom_property_inclusion_for_org" =>
      :create_oidc_custom_property_inclusion_for_org,
    "create_or_update_environment" => :create_or_update_environment,
    "create_or_update_environment_secret" => :create_or_update_environment_secret,
    "create_or_update_file_contents" => :create_or_update_file_contents,
    "create_or_update_org_secret" => :create_or_update_org_secret,
    "create_or_update_repo_secret" => :create_or_update_repo_secret,
    "create_or_update_secret_for_authenticated_user" =>
      :create_or_update_secret_for_authenticated_user,
    "create_org_private_registry" => :create_org_private_registry,
    "create_org_ruleset" => :create_org_ruleset,
    "create_org_variable" => :create_org_variable,
    "create_pages_deployment" => :create_pages_deployment,
    "create_pages_site" => :create_pages_site,
    "create_private_vulnerability_report" => :create_private_vulnerability_report,
    "create_public_ssh_key_for_authenticated_user" =>
      :create_public_ssh_key_for_authenticated_user,
    "create_push_protection_bypass" => :create_push_protection_bypass,
    "create_ref" => :create_ref,
    "create_registration_token_for_org" => :create_registration_token_for_org,
    "create_registration_token_for_repo" => :create_registration_token_for_repo,
    "create_release" => :create_release,
    "create_remove_token_for_org" => :create_remove_token_for_org,
    "create_remove_token_for_repo" => :create_remove_token_for_repo,
    "create_reply_for_review_comment" => :create_reply_for_review_comment,
    "create_repo_ruleset" => :create_repo_ruleset,
    "create_repo_variable" => :create_repo_variable,
    "create_repository_advisory" => :create_repository_advisory,
    "create_repository_advisory_cve_request" => :create_repository_advisory_cve_request,
    "create_repository_snapshot" => :create_repository_snapshot,
    "create_review" => :create_review,
    "create_review_comment" => :create_review_comment,
    "create_self_hosted_runner_group_for_org" => :create_self_hosted_runner_group_for_org,
    "create_ssh_signing_key_for_authenticated_user" =>
      :create_ssh_signing_key_for_authenticated_user,
    "create_suite" => :create_suite,
    "create_tag" => :create_tag,
    "create_tree" => :create_tree,
    "create_using_template" => :create_using_template,
    "create_variant_analysis" => :create_variant_analysis,
    "create_view_for_org" => :create_view_for_org,
    "create_view_for_user" => :create_view_for_user,
    "create_webhook" => :create_webhook,
    "create_with_pr_for_authenticated_user" => :create_with_pr_for_authenticated_user,
    "create_with_repo_for_authenticated_user" => :create_with_repo_for_authenticated_user,
    "create_workflow_dispatch" => :create_workflow_dispatch,
    "custom_properties_for_repos_create_or_update_organization_definition" =>
      :custom_properties_for_repos_create_or_update_organization_definition,
    "custom_properties_for_repos_create_or_update_organization_definitions" =>
      :custom_properties_for_repos_create_or_update_organization_definitions,
    "custom_properties_for_repos_create_or_update_organization_values" =>
      :custom_properties_for_repos_create_or_update_organization_values,
    "custom_properties_for_repos_create_or_update_repository_values" =>
      :custom_properties_for_repos_create_or_update_repository_values,
    "custom_properties_for_repos_delete_organization_definition" =>
      :custom_properties_for_repos_delete_organization_definition,
    "custom_properties_for_repos_get_organization_definition" =>
      :custom_properties_for_repos_get_organization_definition,
    "custom_properties_for_repos_get_organization_definitions" =>
      :custom_properties_for_repos_get_organization_definitions,
    "custom_properties_for_repos_get_organization_values" =>
      :custom_properties_for_repos_get_organization_values,
    "custom_properties_for_repos_get_repository_values" =>
      :custom_properties_for_repos_get_repository_values,
    "decline_invitation_for_authenticated_user" => :decline_invitation_for_authenticated_user,
    "delete" => :delete,
    "delete_access_restrictions" => :delete_access_restrictions,
    "delete_actions_cache_by_id" => :delete_actions_cache_by_id,
    "delete_actions_cache_by_key" => :delete_actions_cache_by_key,
    "delete_admin_branch_protection" => :delete_admin_branch_protection,
    "delete_an_environment" => :delete_an_environment,
    "delete_analysis" => :delete_analysis,
    "delete_archive_for_authenticated_user" => :delete_archive_for_authenticated_user,
    "delete_archive_for_org" => :delete_archive_for_org,
    "delete_artifact" => :delete_artifact,
    "delete_attestations_bulk" => :delete_attestations_bulk,
    "delete_attestations_by_id" => :delete_attestations_by_id,
    "delete_attestations_by_subject_digest" => :delete_attestations_by_subject_digest,
    "delete_authorization" => :delete_authorization,
    "delete_autolink" => :delete_autolink,
    "delete_branch_protection" => :delete_branch_protection,
    "delete_budget_org" => :delete_budget_org,
    "delete_campaign" => :delete_campaign,
    "delete_codeql_database" => :delete_codeql_database,
    "delete_codespaces_access_users" => :delete_codespaces_access_users,
    "delete_comment" => :delete_comment,
    "delete_commit_comment" => :delete_commit_comment,
    "delete_commit_signature_protection" => :delete_commit_signature_protection,
    "delete_configuration" => :delete_configuration,
    "delete_configuration_for_enterprise" => :delete_configuration_for_enterprise,
    "delete_custom_image_from_org" => :delete_custom_image_from_org,
    "delete_custom_image_version_from_org" => :delete_custom_image_version_from_org,
    "delete_deploy_key" => :delete_deploy_key,
    "delete_deployment" => :delete_deployment,
    "delete_deployment_branch_policy" => :delete_deployment_branch_policy,
    "delete_email_for_authenticated_user" => :delete_email_for_authenticated_user,
    "delete_environment_secret" => :delete_environment_secret,
    "delete_environment_variable" => :delete_environment_variable,
    "delete_file" => :delete_file,
    "delete_for_authenticated_user" => :delete_for_authenticated_user,
    "delete_for_commit_comment" => :delete_for_commit_comment,
    "delete_for_issue" => :delete_for_issue,
    "delete_for_issue_comment" => :delete_for_issue_comment,
    "delete_for_pull_request_comment" => :delete_for_pull_request_comment,
    "delete_for_release" => :delete_for_release,
    "delete_from_organization" => :delete_from_organization,
    "delete_gpg_key_for_authenticated_user" => :delete_gpg_key_for_authenticated_user,
    "delete_hosted_runner_for_org" => :delete_hosted_runner_for_org,
    "delete_in_org" => :delete_in_org,
    "delete_installation" => :delete_installation,
    "delete_invitation" => :delete_invitation,
    "delete_issue_field" => :delete_issue_field,
    "delete_issue_field_value" => :delete_issue_field_value,
    "delete_issue_type" => :delete_issue_type,
    "delete_item_for_org" => :delete_item_for_org,
    "delete_item_for_user" => :delete_item_for_user,
    "delete_label" => :delete_label,
    "delete_legacy" => :delete_legacy,
    "delete_milestone" => :delete_milestone,
    "delete_network_configuration_from_org" => :delete_network_configuration_from_org,
    "delete_oidc_custom_property_inclusion_for_enterprise" =>
      :delete_oidc_custom_property_inclusion_for_enterprise,
    "delete_oidc_custom_property_inclusion_for_org" =>
      :delete_oidc_custom_property_inclusion_for_org,
    "delete_org_private_registry" => :delete_org_private_registry,
    "delete_org_ruleset" => :delete_org_ruleset,
    "delete_org_secret" => :delete_org_secret,
    "delete_org_variable" => :delete_org_variable,
    "delete_package_for_authenticated_user" => :delete_package_for_authenticated_user,
    "delete_package_for_org" => :delete_package_for_org,
    "delete_package_for_user" => :delete_package_for_user,
    "delete_package_version_for_authenticated_user" =>
      :delete_package_version_for_authenticated_user,
    "delete_package_version_for_org" => :delete_package_version_for_org,
    "delete_package_version_for_user" => :delete_package_version_for_user,
    "delete_pages_site" => :delete_pages_site,
    "delete_pending_review" => :delete_pending_review,
    "delete_public_ssh_key_for_authenticated_user" =>
      :delete_public_ssh_key_for_authenticated_user,
    "delete_pull_request_review_protection" => :delete_pull_request_review_protection,
    "delete_ref" => :delete_ref,
    "delete_release" => :delete_release,
    "delete_release_asset" => :delete_release_asset,
    "delete_repo_ruleset" => :delete_repo_ruleset,
    "delete_repo_secret" => :delete_repo_secret,
    "delete_repo_subscription" => :delete_repo_subscription,
    "delete_repo_variable" => :delete_repo_variable,
    "delete_review_comment" => :delete_review_comment,
    "delete_secret_for_authenticated_user" => :delete_secret_for_authenticated_user,
    "delete_self_hosted_runner_from_org" => :delete_self_hosted_runner_from_org,
    "delete_self_hosted_runner_from_repo" => :delete_self_hosted_runner_from_repo,
    "delete_self_hosted_runner_group_from_org" => :delete_self_hosted_runner_group_from_org,
    "delete_social_account_for_authenticated_user" =>
      :delete_social_account_for_authenticated_user,
    "delete_ssh_signing_key_for_authenticated_user" =>
      :delete_ssh_signing_key_for_authenticated_user,
    "delete_thread_subscription" => :delete_thread_subscription,
    "delete_token" => :delete_token,
    "delete_webhook" => :delete_webhook,
    "delete_workflow_run" => :delete_workflow_run,
    "delete_workflow_run_logs" => :delete_workflow_run_logs,
    "detach_configuration" => :detach_configuration,
    "diff_range" => :diff_range,
    "disable_automated_security_fixes" => :disable_automated_security_fixes,
    "disable_deployment_protection_rule" => :disable_deployment_protection_rule,
    "disable_immutable_releases" => :disable_immutable_releases,
    "disable_private_vulnerability_reporting" => :disable_private_vulnerability_reporting,
    "disable_selected_repository_github_actions_organization" =>
      :disable_selected_repository_github_actions_organization,
    "disable_selected_repository_immutable_releases_organization" =>
      :disable_selected_repository_immutable_releases_organization,
    "disable_selected_repository_self_hosted_runners_organization" =>
      :disable_selected_repository_self_hosted_runners_organization,
    "disable_vulnerability_alerts" => :disable_vulnerability_alerts,
    "disable_workflow" => :disable_workflow,
    "dismiss_review" => :dismiss_review,
    "download_archive_for_org" => :download_archive_for_org,
    "download_artifact" => :download_artifact,
    "download_job_logs_for_workflow_run" => :download_job_logs_for_workflow_run,
    "download_tarball_archive" => :download_tarball_archive,
    "download_workflow_run_attempt_logs" => :download_workflow_run_attempt_logs,
    "download_workflow_run_logs" => :download_workflow_run_logs,
    "download_zipball_archive" => :download_zipball_archive,
    "enable_automated_security_fixes" => :enable_automated_security_fixes,
    "enable_immutable_releases" => :enable_immutable_releases,
    "enable_or_disable_security_product_on_all_org_repos" =>
      :enable_or_disable_security_product_on_all_org_repos,
    "enable_private_vulnerability_reporting" => :enable_private_vulnerability_reporting,
    "enable_selected_repository_github_actions_organization" =>
      :enable_selected_repository_github_actions_organization,
    "enable_selected_repository_immutable_releases_organization" =>
      :enable_selected_repository_immutable_releases_organization,
    "enable_selected_repository_self_hosted_runners_organization" =>
      :enable_selected_repository_self_hosted_runners_organization,
    "enable_vulnerability_alerts" => :enable_vulnerability_alerts,
    "enable_workflow" => :enable_workflow,
    "export_for_authenticated_user" => :export_for_authenticated_user,
    "export_sbom" => :export_sbom,
    "follow" => :follow,
    "force_cancel_workflow_run" => :force_cancel_workflow_run,
    "fork" => :fork,
    "generate_release_notes" => :generate_release_notes,
    "generate_runner_jitconfig_for_org" => :generate_runner_jitconfig_for_org,
    "generate_runner_jitconfig_for_repo" => :generate_runner_jitconfig_for_repo,
    "get" => :get,
    "get_a_classroom" => :get_a_classroom,
    "get_access_restrictions" => :get_access_restrictions,
    "get_actions_cache_list" => :get_actions_cache_list,
    "get_actions_cache_retention_limit_for_enterprise" =>
      :get_actions_cache_retention_limit_for_enterprise,
    "get_actions_cache_retention_limit_for_organization" =>
      :get_actions_cache_retention_limit_for_organization,
    "get_actions_cache_retention_limit_for_repository" =>
      :get_actions_cache_retention_limit_for_repository,
    "get_actions_cache_storage_limit_for_enterprise" =>
      :get_actions_cache_storage_limit_for_enterprise,
    "get_actions_cache_storage_limit_for_organization" =>
      :get_actions_cache_storage_limit_for_organization,
    "get_actions_cache_storage_limit_for_repository" =>
      :get_actions_cache_storage_limit_for_repository,
    "get_actions_cache_usage" => :get_actions_cache_usage,
    "get_actions_cache_usage_by_repo_for_org" => :get_actions_cache_usage_by_repo_for_org,
    "get_actions_cache_usage_for_org" => :get_actions_cache_usage_for_org,
    "get_admin_branch_protection" => :get_admin_branch_protection,
    "get_alert" => :get_alert,
    "get_all_budgets_org" => :get_all_budgets_org,
    "get_all_codes_of_conduct" => :get_all_codes_of_conduct,
    "get_all_commonly_used" => :get_all_commonly_used,
    "get_all_deployment_protection_rules" => :get_all_deployment_protection_rules,
    "get_all_environments" => :get_all_environments,
    "get_all_package_versions_for_package_owned_by_authenticated_user" =>
      :get_all_package_versions_for_package_owned_by_authenticated_user,
    "get_all_package_versions_for_package_owned_by_org" =>
      :get_all_package_versions_for_package_owned_by_org,
    "get_all_package_versions_for_package_owned_by_user" =>
      :get_all_package_versions_for_package_owned_by_user,
    "get_all_status_check_contexts" => :get_all_status_check_contexts,
    "get_all_templates" => :get_all_templates,
    "get_all_topics" => :get_all_topics,
    "get_all_versions" => :get_all_versions,
    "get_allowed_actions_organization" => :get_allowed_actions_organization,
    "get_allowed_actions_repository" => :get_allowed_actions_repository,
    "get_an_assignment" => :get_an_assignment,
    "get_analysis" => :get_analysis,
    "get_apps_with_access_to_protected_branch" => :get_apps_with_access_to_protected_branch,
    "get_archive_for_authenticated_user" => :get_archive_for_authenticated_user,
    "get_artifact" => :get_artifact,
    "get_artifact_and_log_retention_settings_organization" =>
      :get_artifact_and_log_retention_settings_organization,
    "get_artifact_and_log_retention_settings_repository" =>
      :get_artifact_and_log_retention_settings_repository,
    "get_assignment" => :get_assignment,
    "get_assignment_grades" => :get_assignment_grades,
    "get_assignments" => :get_assignments,
    "get_authenticated" => :get_authenticated,
    "get_autofix" => :get_autofix,
    "get_autolink" => :get_autolink,
    "get_blob" => :get_blob,
    "get_branch" => :get_branch,
    "get_branch_protection" => :get_branch_protection,
    "get_branch_rules" => :get_branch_rules,
    "get_budget_org" => :get_budget_org,
    "get_by_id" => :get_by_id,
    "get_by_name" => :get_by_name,
    "get_by_slug" => :get_by_slug,
    "get_by_username" => :get_by_username,
    "get_campaign_summary" => :get_campaign_summary,
    "get_clones" => :get_clones,
    "get_code_frequency_stats" => :get_code_frequency_stats,
    "get_codeql_database" => :get_codeql_database,
    "get_codespaces_for_user_in_org" => :get_codespaces_for_user_in_org,
    "get_collaborator_permission_level" => :get_collaborator_permission_level,
    "get_combined_status_for_ref" => :get_combined_status_for_ref,
    "get_comment" => :get_comment,
    "get_commit" => :get_commit,
    "get_commit_activity_stats" => :get_commit_activity_stats,
    "get_commit_authors" => :get_commit_authors,
    "get_commit_comment" => :get_commit_comment,
    "get_commit_signature_protection" => :get_commit_signature_protection,
    "get_community_profile_metrics" => :get_community_profile_metrics,
    "get_conduct_code" => :get_conduct_code,
    "get_configuration" => :get_configuration,
    "get_configuration_for_repository" => :get_configuration_for_repository,
    "get_configurations_for_enterprise" => :get_configurations_for_enterprise,
    "get_configurations_for_org" => :get_configurations_for_org,
    "get_content" => :get_content,
    "get_context_for_user" => :get_context_for_user,
    "get_contributors_stats" => :get_contributors_stats,
    "get_copilot_organization_details" => :get_copilot_organization_details,
    "get_copilot_seat_details_for_user" => :get_copilot_seat_details_for_user,
    "get_custom_deployment_protection_rule" => :get_custom_deployment_protection_rule,
    "get_custom_image_for_org" => :get_custom_image_for_org,
    "get_custom_image_version_for_org" => :get_custom_image_version_for_org,
    "get_custom_oidc_sub_claim_for_repo" => :get_custom_oidc_sub_claim_for_repo,
    "get_default_configurations" => :get_default_configurations,
    "get_default_configurations_for_enterprise" => :get_default_configurations_for_enterprise,
    "get_default_setup" => :get_default_setup,
    "get_deploy_key" => :get_deploy_key,
    "get_deployment" => :get_deployment,
    "get_deployment_branch_policy" => :get_deployment_branch_policy,
    "get_deployment_status" => :get_deployment_status,
    "get_environment" => :get_environment,
    "get_environment_public_key" => :get_environment_public_key,
    "get_environment_secret" => :get_environment_secret,
    "get_environment_variable" => :get_environment_variable,
    "get_event" => :get_event,
    "get_export_details_for_authenticated_user" => :get_export_details_for_authenticated_user,
    "get_feeds" => :get_feeds,
    "get_field_for_org" => :get_field_for_org,
    "get_field_for_user" => :get_field_for_user,
    "get_for_authenticated_user" => :get_for_authenticated_user,
    "get_for_org" => :get_for_org,
    "get_for_repo" => :get_for_repo,
    "get_for_user" => :get_for_user,
    "get_fork_pr_contributor_approval_permissions_organization" =>
      :get_fork_pr_contributor_approval_permissions_organization,
    "get_fork_pr_contributor_approval_permissions_repository" =>
      :get_fork_pr_contributor_approval_permissions_repository,
    "get_github_actions_default_workflow_permissions_organization" =>
      :get_github_actions_default_workflow_permissions_organization,
    "get_github_actions_default_workflow_permissions_repository" =>
      :get_github_actions_default_workflow_permissions_repository,
    "get_github_actions_permissions_organization" => :get_github_actions_permissions_organization,
    "get_github_actions_permissions_repository" => :get_github_actions_permissions_repository,
    "get_github_billing_premium_request_usage_report_org" =>
      :get_github_billing_premium_request_usage_report_org,
    "get_github_billing_premium_request_usage_report_user" =>
      :get_github_billing_premium_request_usage_report_user,
    "get_github_billing_usage_report_org" => :get_github_billing_usage_report_org,
    "get_github_billing_usage_report_user" => :get_github_billing_usage_report_user,
    "get_github_billing_usage_summary_report_org" => :get_github_billing_usage_summary_report_org,
    "get_github_billing_usage_summary_report_user" =>
      :get_github_billing_usage_summary_report_user,
    "get_global_advisory" => :get_global_advisory,
    "get_gpg_key_for_authenticated_user" => :get_gpg_key_for_authenticated_user,
    "get_hosted_runner_for_org" => :get_hosted_runner_for_org,
    "get_hosted_runners_github_owned_images_for_org" =>
      :get_hosted_runners_github_owned_images_for_org,
    "get_hosted_runners_limits_for_org" => :get_hosted_runners_limits_for_org,
    "get_hosted_runners_machine_specs_for_org" => :get_hosted_runners_machine_specs_for_org,
    "get_hosted_runners_partner_images_for_org" => :get_hosted_runners_partner_images_for_org,
    "get_hosted_runners_platforms_for_org" => :get_hosted_runners_platforms_for_org,
    "get_immutable_releases_settings" => :get_immutable_releases_settings,
    "get_immutable_releases_settings_repositories" =>
      :get_immutable_releases_settings_repositories,
    "get_import_status" => :get_import_status,
    "get_installation" => :get_installation,
    "get_job_for_workflow_run" => :get_job_for_workflow_run,
    "get_label" => :get_label,
    "get_large_files" => :get_large_files,
    "get_latest_pages_build" => :get_latest_pages_build,
    "get_latest_release" => :get_latest_release,
    "get_legacy" => :get_legacy,
    "get_member_legacy" => :get_member_legacy,
    "get_membership_for_authenticated_user" => :get_membership_for_authenticated_user,
    "get_membership_for_user" => :get_membership_for_user,
    "get_membership_for_user_in_org" => :get_membership_for_user_in_org,
    "get_membership_for_user_legacy" => :get_membership_for_user_legacy,
    "get_milestone" => :get_milestone,
    "get_network_configuration_for_org" => :get_network_configuration_for_org,
    "get_network_settings_for_org" => :get_network_settings_for_org,
    "get_octocat" => :get_octocat,
    "get_oidc_custom_sub_template_for_org" => :get_oidc_custom_sub_template_for_org,
    "get_org_installation" => :get_org_installation,
    "get_org_item" => :get_org_item,
    "get_org_private_registry" => :get_org_private_registry,
    "get_org_public_key" => :get_org_public_key,
    "get_org_role" => :get_org_role,
    "get_org_rule_suite" => :get_org_rule_suite,
    "get_org_rule_suites" => :get_org_rule_suites,
    "get_org_ruleset" => :get_org_ruleset,
    "get_org_ruleset_history" => :get_org_ruleset_history,
    "get_org_ruleset_version" => :get_org_ruleset_version,
    "get_org_rulesets" => :get_org_rulesets,
    "get_org_secret" => :get_org_secret,
    "get_org_variable" => :get_org_variable,
    "get_package_for_authenticated_user" => :get_package_for_authenticated_user,
    "get_package_for_organization" => :get_package_for_organization,
    "get_package_for_user" => :get_package_for_user,
    "get_package_version_for_authenticated_user" => :get_package_version_for_authenticated_user,
    "get_package_version_for_organization" => :get_package_version_for_organization,
    "get_package_version_for_user" => :get_package_version_for_user,
    "get_pages" => :get_pages,
    "get_pages_build" => :get_pages_build,
    "get_pages_deployment" => :get_pages_deployment,
    "get_pages_health_check" => :get_pages_health_check,
    "get_parent" => :get_parent,
    "get_participation_stats" => :get_participation_stats,
    "get_pending_deployments_for_run" => :get_pending_deployments_for_run,
    "get_private_repo_fork_pr_workflows_settings_organization" =>
      :get_private_repo_fork_pr_workflows_settings_organization,
    "get_private_repo_fork_pr_workflows_settings_repository" =>
      :get_private_repo_fork_pr_workflows_settings_repository,
    "get_public_key_for_authenticated_user" => :get_public_key_for_authenticated_user,
    "get_public_ssh_key_for_authenticated_user" => :get_public_ssh_key_for_authenticated_user,
    "get_pull_request_review_protection" => :get_pull_request_review_protection,
    "get_punch_card_stats" => :get_punch_card_stats,
    "get_readme" => :get_readme,
    "get_readme_in_directory" => :get_readme_in_directory,
    "get_ref" => :get_ref,
    "get_release" => :get_release,
    "get_release_asset" => :get_release_asset,
    "get_release_by_tag" => :get_release_by_tag,
    "get_repo_installation" => :get_repo_installation,
    "get_repo_public_key" => :get_repo_public_key,
    "get_repo_rule_suite" => :get_repo_rule_suite,
    "get_repo_rule_suites" => :get_repo_rule_suites,
    "get_repo_ruleset" => :get_repo_ruleset,
    "get_repo_ruleset_history" => :get_repo_ruleset_history,
    "get_repo_ruleset_version" => :get_repo_ruleset_version,
    "get_repo_rulesets" => :get_repo_rulesets,
    "get_repo_secret" => :get_repo_secret,
    "get_repo_subscription" => :get_repo_subscription,
    "get_repo_variable" => :get_repo_variable,
    "get_repositories_for_configuration" => :get_repositories_for_configuration,
    "get_repositories_for_enterprise_configuration" =>
      :get_repositories_for_enterprise_configuration,
    "get_repository_advisory" => :get_repository_advisory,
    "get_restrictions_for_authenticated_user" => :get_restrictions_for_authenticated_user,
    "get_restrictions_for_org" => :get_restrictions_for_org,
    "get_restrictions_for_repo" => :get_restrictions_for_repo,
    "get_review" => :get_review,
    "get_review_comment" => :get_review_comment,
    "get_reviews_for_run" => :get_reviews_for_run,
    "get_revision" => :get_revision,
    "get_route_stats_by_actor" => :get_route_stats_by_actor,
    "get_sarif" => :get_sarif,
    "get_scan_history" => :get_scan_history,
    "get_secret_for_authenticated_user" => :get_secret_for_authenticated_user,
    "get_self_hosted_runner_for_org" => :get_self_hosted_runner_for_org,
    "get_self_hosted_runner_for_repo" => :get_self_hosted_runner_for_repo,
    "get_self_hosted_runner_group_for_org" => :get_self_hosted_runner_group_for_org,
    "get_self_hosted_runners_permissions_organization" =>
      :get_self_hosted_runners_permissions_organization,
    "get_single_configuration_for_enterprise" => :get_single_configuration_for_enterprise,
    "get_ssh_signing_key_for_authenticated_user" => :get_ssh_signing_key_for_authenticated_user,
    "get_status_checks_protection" => :get_status_checks_protection,
    "get_status_for_authenticated_user" => :get_status_for_authenticated_user,
    "get_status_for_org" => :get_status_for_org,
    "get_subject_stats" => :get_subject_stats,
    "get_subscription_plan_for_account" => :get_subscription_plan_for_account,
    "get_subscription_plan_for_account_stubbed" => :get_subscription_plan_for_account_stubbed,
    "get_suite" => :get_suite,
    "get_summary_stats" => :get_summary_stats,
    "get_summary_stats_by_actor" => :get_summary_stats_by_actor,
    "get_summary_stats_by_user" => :get_summary_stats_by_user,
    "get_tag" => :get_tag,
    "get_teams_with_access_to_protected_branch" => :get_teams_with_access_to_protected_branch,
    "get_template" => :get_template,
    "get_thread" => :get_thread,
    "get_thread_subscription_for_authenticated_user" =>
      :get_thread_subscription_for_authenticated_user,
    "get_time_stats" => :get_time_stats,
    "get_time_stats_by_actor" => :get_time_stats_by_actor,
    "get_time_stats_by_user" => :get_time_stats_by_user,
    "get_top_paths" => :get_top_paths,
    "get_top_referrers" => :get_top_referrers,
    "get_tree" => :get_tree,
    "get_user_installation" => :get_user_installation,
    "get_user_item" => :get_user_item,
    "get_user_stats" => :get_user_stats,
    "get_users_with_access_to_protected_branch" => :get_users_with_access_to_protected_branch,
    "get_variant_analysis" => :get_variant_analysis,
    "get_variant_analysis_repo_task" => :get_variant_analysis_repo_task,
    "get_views" => :get_views,
    "get_webhook" => :get_webhook,
    "get_webhook_config_for_app" => :get_webhook_config_for_app,
    "get_webhook_config_for_org" => :get_webhook_config_for_org,
    "get_webhook_config_for_repo" => :get_webhook_config_for_repo,
    "get_webhook_delivery" => :get_webhook_delivery,
    "get_workflow" => :get_workflow,
    "get_workflow_access_to_repository" => :get_workflow_access_to_repository,
    "get_workflow_run" => :get_workflow_run,
    "get_workflow_run_attempt" => :get_workflow_run_attempt,
    "get_workflow_run_usage" => :get_workflow_run_usage,
    "get_workflow_usage" => :get_workflow_usage,
    "get_zen" => :get_zen,
    "issues_and_pull_requests" => :issues_and_pull_requests,
    "labels" => :labels,
    "list" => :list,
    "list_accepted_assignments_for_an_assignment" => :list_accepted_assignments_for_an_assignment,
    "list_accounts_for_plan" => :list_accounts_for_plan,
    "list_accounts_for_plan_stubbed" => :list_accounts_for_plan_stubbed,
    "list_activities" => :list_activities,
    "list_alert_instances" => :list_alert_instances,
    "list_alerts_for_enterprise" => :list_alerts_for_enterprise,
    "list_alerts_for_org" => :list_alerts_for_org,
    "list_alerts_for_repo" => :list_alerts_for_repo,
    "list_annotations" => :list_annotations,
    "list_app_installations" => :list_app_installations,
    "list_artifact_deployment_records" => :list_artifact_deployment_records,
    "list_artifact_storage_records" => :list_artifact_storage_records,
    "list_artifacts_for_repo" => :list_artifacts_for_repo,
    "list_assignees" => :list_assignees,
    "list_assignments_for_a_classroom" => :list_assignments_for_a_classroom,
    "list_attestation_repositories" => :list_attestation_repositories,
    "list_attestations" => :list_attestations,
    "list_attestations_bulk" => :list_attestations_bulk,
    "list_autolinks" => :list_autolinks,
    "list_blocked_by_authenticated_user" => :list_blocked_by_authenticated_user,
    "list_blocked_users" => :list_blocked_users,
    "list_branches" => :list_branches,
    "list_branches_for_head_commit" => :list_branches_for_head_commit,
    "list_child_in_org" => :list_child_in_org,
    "list_child_legacy" => :list_child_legacy,
    "list_classrooms" => :list_classrooms,
    "list_codeql_databases" => :list_codeql_databases,
    "list_collaborators" => :list_collaborators,
    "list_comments" => :list_comments,
    "list_comments_for_commit" => :list_comments_for_commit,
    "list_comments_for_repo" => :list_comments_for_repo,
    "list_comments_for_review" => :list_comments_for_review,
    "list_commit_comments_for_repo" => :list_commit_comments_for_repo,
    "list_commit_statuses_for_ref" => :list_commit_statuses_for_ref,
    "list_commits" => :list_commits,
    "list_contributors" => :list_contributors,
    "list_copilot_seats" => :list_copilot_seats,
    "list_custom_deployment_rule_integrations" => :list_custom_deployment_rule_integrations,
    "list_custom_image_versions_for_org" => :list_custom_image_versions_for_org,
    "list_custom_images_for_org" => :list_custom_images_for_org,
    "list_dependencies_blocked_by" => :list_dependencies_blocked_by,
    "list_dependencies_blocking" => :list_dependencies_blocking,
    "list_deploy_keys" => :list_deploy_keys,
    "list_deployment_branch_policies" => :list_deployment_branch_policies,
    "list_deployment_statuses" => :list_deployment_statuses,
    "list_deployments" => :list_deployments,
    "list_devcontainers_in_repository_for_authenticated_user" =>
      :list_devcontainers_in_repository_for_authenticated_user,
    "list_docker_migration_conflicting_packages_for_authenticated_user" =>
      :list_docker_migration_conflicting_packages_for_authenticated_user,
    "list_docker_migration_conflicting_packages_for_organization" =>
      :list_docker_migration_conflicting_packages_for_organization,
    "list_docker_migration_conflicting_packages_for_user" =>
      :list_docker_migration_conflicting_packages_for_user,
    "list_emails_for_authenticated_user" => :list_emails_for_authenticated_user,
    "list_environment_secrets" => :list_environment_secrets,
    "list_environment_variables" => :list_environment_variables,
    "list_events" => :list_events,
    "list_events_for_authenticated_user" => :list_events_for_authenticated_user,
    "list_events_for_repo" => :list_events_for_repo,
    "list_events_for_timeline" => :list_events_for_timeline,
    "list_failed_invitations" => :list_failed_invitations,
    "list_fields_for_org" => :list_fields_for_org,
    "list_fields_for_user" => :list_fields_for_user,
    "list_files" => :list_files,
    "list_followed_by_authenticated_user" => :list_followed_by_authenticated_user,
    "list_followers_for_authenticated_user" => :list_followers_for_authenticated_user,
    "list_followers_for_user" => :list_followers_for_user,
    "list_following_for_user" => :list_following_for_user,
    "list_for_authenticated_user" => :list_for_authenticated_user,
    "list_for_commit_comment" => :list_for_commit_comment,
    "list_for_issue" => :list_for_issue,
    "list_for_issue_comment" => :list_for_issue_comment,
    "list_for_org" => :list_for_org,
    "list_for_pull_request_review_comment" => :list_for_pull_request_review_comment,
    "list_for_ref" => :list_for_ref,
    "list_for_release" => :list_for_release,
    "list_for_repo" => :list_for_repo,
    "list_for_suite" => :list_for_suite,
    "list_for_user" => :list_for_user,
    "list_forks" => :list_forks,
    "list_github_hosted_runners_in_group_for_org" => :list_github_hosted_runners_in_group_for_org,
    "list_global_advisories" => :list_global_advisories,
    "list_gpg_keys_for_authenticated_user" => :list_gpg_keys_for_authenticated_user,
    "list_gpg_keys_for_user" => :list_gpg_keys_for_user,
    "list_hosted_runners_for_org" => :list_hosted_runners_for_org,
    "list_in_organization" => :list_in_organization,
    "list_in_repository_for_authenticated_user" => :list_in_repository_for_authenticated_user,
    "list_installation_repos_for_authenticated_user" =>
      :list_installation_repos_for_authenticated_user,
    "list_installation_requests_for_authenticated_app" =>
      :list_installation_requests_for_authenticated_app,
    "list_installations" => :list_installations,
    "list_installations_for_authenticated_user" => :list_installations_for_authenticated_user,
    "list_invitation_teams" => :list_invitation_teams,
    "list_invitations" => :list_invitations,
    "list_invitations_for_authenticated_user" => :list_invitations_for_authenticated_user,
    "list_issue_field_values_for_issue" => :list_issue_field_values_for_issue,
    "list_issue_fields" => :list_issue_fields,
    "list_issue_types" => :list_issue_types,
    "list_items_for_org" => :list_items_for_org,
    "list_items_for_user" => :list_items_for_user,
    "list_jobs_for_workflow_run" => :list_jobs_for_workflow_run,
    "list_jobs_for_workflow_run_attempt" => :list_jobs_for_workflow_run_attempt,
    "list_labels_for_milestone" => :list_labels_for_milestone,
    "list_labels_for_repo" => :list_labels_for_repo,
    "list_labels_for_self_hosted_runner_for_org" => :list_labels_for_self_hosted_runner_for_org,
    "list_labels_for_self_hosted_runner_for_repo" => :list_labels_for_self_hosted_runner_for_repo,
    "list_labels_on_issue" => :list_labels_on_issue,
    "list_languages" => :list_languages,
    "list_locations_for_alert" => :list_locations_for_alert,
    "list_matching_refs" => :list_matching_refs,
    "list_members" => :list_members,
    "list_members_in_org" => :list_members_in_org,
    "list_members_legacy" => :list_members_legacy,
    "list_memberships_for_authenticated_user" => :list_memberships_for_authenticated_user,
    "list_milestones" => :list_milestones,
    "list_network_configurations_for_org" => :list_network_configurations_for_org,
    "list_notifications_for_authenticated_user" => :list_notifications_for_authenticated_user,
    "list_oidc_custom_property_inclusions_for_enterprise" =>
      :list_oidc_custom_property_inclusions_for_enterprise,
    "list_oidc_custom_property_inclusions_for_org" =>
      :list_oidc_custom_property_inclusions_for_org,
    "list_org_campaigns" => :list_org_campaigns,
    "list_org_events_for_authenticated_user" => :list_org_events_for_authenticated_user,
    "list_org_pattern_configs" => :list_org_pattern_configs,
    "list_org_private_registries" => :list_org_private_registries,
    "list_org_repository_advisories" => :list_org_repository_advisories,
    "list_org_role_teams" => :list_org_role_teams,
    "list_org_role_users" => :list_org_role_users,
    "list_org_roles" => :list_org_roles,
    "list_org_secrets" => :list_org_secrets,
    "list_org_variables" => :list_org_variables,
    "list_outside_collaborators" => :list_outside_collaborators,
    "list_packages_for_authenticated_user" => :list_packages_for_authenticated_user,
    "list_packages_for_organization" => :list_packages_for_organization,
    "list_packages_for_user" => :list_packages_for_user,
    "list_pages_builds" => :list_pages_builds,
    "list_pat_grant_repositories" => :list_pat_grant_repositories,
    "list_pat_grant_request_repositories" => :list_pat_grant_request_repositories,
    "list_pat_grant_requests" => :list_pat_grant_requests,
    "list_pat_grants" => :list_pat_grants,
    "list_pending_invitations" => :list_pending_invitations,
    "list_pending_invitations_in_org" => :list_pending_invitations_in_org,
    "list_pending_invitations_legacy" => :list_pending_invitations_legacy,
    "list_plans" => :list_plans,
    "list_plans_stubbed" => :list_plans_stubbed,
    "list_public" => :list_public,
    "list_public_emails_for_authenticated_user" => :list_public_emails_for_authenticated_user,
    "list_public_events" => :list_public_events,
    "list_public_events_for_repo_network" => :list_public_events_for_repo_network,
    "list_public_events_for_user" => :list_public_events_for_user,
    "list_public_keys_for_user" => :list_public_keys_for_user,
    "list_public_members" => :list_public_members,
    "list_public_org_events" => :list_public_org_events,
    "list_public_ssh_keys_for_authenticated_user" => :list_public_ssh_keys_for_authenticated_user,
    "list_pull_requests_associated_with_commit" => :list_pull_requests_associated_with_commit,
    "list_received_events_for_user" => :list_received_events_for_user,
    "list_received_public_events_for_user" => :list_received_public_events_for_user,
    "list_recent_analyses" => :list_recent_analyses,
    "list_release_assets" => :list_release_assets,
    "list_releases" => :list_releases,
    "list_repo_access_to_self_hosted_runner_group_in_org" =>
      :list_repo_access_to_self_hosted_runner_group_in_org,
    "list_repo_events" => :list_repo_events,
    "list_repo_notifications_for_authenticated_user" =>
      :list_repo_notifications_for_authenticated_user,
    "list_repo_organization_secrets" => :list_repo_organization_secrets,
    "list_repo_organization_variables" => :list_repo_organization_variables,
    "list_repo_secrets" => :list_repo_secrets,
    "list_repo_variables" => :list_repo_variables,
    "list_repo_workflows" => :list_repo_workflows,
    "list_repos_accessible_to_installation" => :list_repos_accessible_to_installation,
    "list_repos_for_authenticated_user" => :list_repos_for_authenticated_user,
    "list_repos_for_org" => :list_repos_for_org,
    "list_repos_in_org" => :list_repos_in_org,
    "list_repos_legacy" => :list_repos_legacy,
    "list_repos_starred_by_authenticated_user" => :list_repos_starred_by_authenticated_user,
    "list_repos_starred_by_user" => :list_repos_starred_by_user,
    "list_repos_watched_by_user" => :list_repos_watched_by_user,
    "list_repositories_for_secret_for_authenticated_user" =>
      :list_repositories_for_secret_for_authenticated_user,
    "list_repository_advisories" => :list_repository_advisories,
    "list_requested_reviewers" => :list_requested_reviewers,
    "list_review_comments" => :list_review_comments,
    "list_review_comments_for_repo" => :list_review_comments_for_repo,
    "list_reviews" => :list_reviews,
    "list_runner_applications_for_org" => :list_runner_applications_for_org,
    "list_runner_applications_for_repo" => :list_runner_applications_for_repo,
    "list_secrets_for_authenticated_user" => :list_secrets_for_authenticated_user,
    "list_security_manager_teams" => :list_security_manager_teams,
    "list_selected_repos_for_org_secret" => :list_selected_repos_for_org_secret,
    "list_selected_repos_for_org_variable" => :list_selected_repos_for_org_variable,
    "list_selected_repositories_enabled_github_actions_organization" =>
      :list_selected_repositories_enabled_github_actions_organization,
    "list_selected_repositories_self_hosted_runners_organization" =>
      :list_selected_repositories_self_hosted_runners_organization,
    "list_self_hosted_runner_groups_for_org" => :list_self_hosted_runner_groups_for_org,
    "list_self_hosted_runners_for_org" => :list_self_hosted_runners_for_org,
    "list_self_hosted_runners_for_repo" => :list_self_hosted_runners_for_repo,
    "list_self_hosted_runners_in_group_for_org" => :list_self_hosted_runners_in_group_for_org,
    "list_social_accounts_for_authenticated_user" => :list_social_accounts_for_authenticated_user,
    "list_social_accounts_for_user" => :list_social_accounts_for_user,
    "list_ssh_signing_keys_for_authenticated_user" =>
      :list_ssh_signing_keys_for_authenticated_user,
    "list_ssh_signing_keys_for_user" => :list_ssh_signing_keys_for_user,
    "list_stargazers_for_repo" => :list_stargazers_for_repo,
    "list_starred" => :list_starred,
    "list_sub_issues" => :list_sub_issues,
    "list_subscriptions_for_authenticated_user" => :list_subscriptions_for_authenticated_user,
    "list_subscriptions_for_authenticated_user_stubbed" =>
      :list_subscriptions_for_authenticated_user_stubbed,
    "list_suites_for_ref" => :list_suites_for_ref,
    "list_tags" => :list_tags,
    "list_teams" => :list_teams,
    "list_view_items_for_org" => :list_view_items_for_org,
    "list_view_items_for_user" => :list_view_items_for_user,
    "list_watched_repos_for_authenticated_user" => :list_watched_repos_for_authenticated_user,
    "list_watchers_for_repo" => :list_watchers_for_repo,
    "list_webhook_deliveries" => :list_webhook_deliveries,
    "list_webhooks" => :list_webhooks,
    "list_workflow_run_artifacts" => :list_workflow_run_artifacts,
    "list_workflow_runs" => :list_workflow_runs,
    "list_workflow_runs_for_repo" => :list_workflow_runs_for_repo,
    "lock" => :lock,
    "map_commit_author" => :map_commit_author,
    "mark_notifications_as_read" => :mark_notifications_as_read,
    "mark_repo_notifications_as_read" => :mark_repo_notifications_as_read,
    "mark_thread_as_done" => :mark_thread_as_done,
    "mark_thread_as_read" => :mark_thread_as_read,
    "merge" => :merge,
    "merge_upstream" => :merge_upstream,
    "pin_comment" => :pin_comment,
    "ping_webhook" => :ping_webhook,
    "pre_flight_with_repo_for_authenticated_user" => :pre_flight_with_repo_for_authenticated_user,
    "publish_for_authenticated_user" => :publish_for_authenticated_user,
    "re_run_job_for_workflow_run" => :re_run_job_for_workflow_run,
    "re_run_workflow" => :re_run_workflow,
    "re_run_workflow_failed_jobs" => :re_run_workflow_failed_jobs,
    "redeliver_webhook_delivery" => :redeliver_webhook_delivery,
    "remove" => :remove,
    "remove_all_custom_labels_from_self_hosted_runner_for_org" =>
      :remove_all_custom_labels_from_self_hosted_runner_for_org,
    "remove_all_custom_labels_from_self_hosted_runner_for_repo" =>
      :remove_all_custom_labels_from_self_hosted_runner_for_repo,
    "remove_all_labels" => :remove_all_labels,
    "remove_app_access_restrictions" => :remove_app_access_restrictions,
    "remove_assignees" => :remove_assignees,
    "remove_collaborator" => :remove_collaborator,
    "remove_custom_label_from_self_hosted_runner_for_org" =>
      :remove_custom_label_from_self_hosted_runner_for_org,
    "remove_custom_label_from_self_hosted_runner_for_repo" =>
      :remove_custom_label_from_self_hosted_runner_for_repo,
    "remove_dependency_blocked_by" => :remove_dependency_blocked_by,
    "remove_label" => :remove_label,
    "remove_member" => :remove_member,
    "remove_member_legacy" => :remove_member_legacy,
    "remove_membership_for_user" => :remove_membership_for_user,
    "remove_membership_for_user_in_org" => :remove_membership_for_user_in_org,
    "remove_membership_for_user_legacy" => :remove_membership_for_user_legacy,
    "remove_outside_collaborator" => :remove_outside_collaborator,
    "remove_public_membership_for_authenticated_user" =>
      :remove_public_membership_for_authenticated_user,
    "remove_repo_access_to_self_hosted_runner_group_in_org" =>
      :remove_repo_access_to_self_hosted_runner_group_in_org,
    "remove_repo_from_installation_for_authenticated_user" =>
      :remove_repo_from_installation_for_authenticated_user,
    "remove_repo_in_org" => :remove_repo_in_org,
    "remove_repo_legacy" => :remove_repo_legacy,
    "remove_repository_for_secret_for_authenticated_user" =>
      :remove_repository_for_secret_for_authenticated_user,
    "remove_requested_reviewers" => :remove_requested_reviewers,
    "remove_restrictions_for_authenticated_user" => :remove_restrictions_for_authenticated_user,
    "remove_restrictions_for_org" => :remove_restrictions_for_org,
    "remove_restrictions_for_repo" => :remove_restrictions_for_repo,
    "remove_security_manager_team" => :remove_security_manager_team,
    "remove_selected_repo_from_org_secret" => :remove_selected_repo_from_org_secret,
    "remove_selected_repo_from_org_variable" => :remove_selected_repo_from_org_variable,
    "remove_self_hosted_runner_from_group_for_org" =>
      :remove_self_hosted_runner_from_group_for_org,
    "remove_status_check_contexts" => :remove_status_check_contexts,
    "remove_status_check_protection" => :remove_status_check_protection,
    "remove_sub_issue" => :remove_sub_issue,
    "remove_team_access_restrictions" => :remove_team_access_restrictions,
    "remove_user_access_restrictions" => :remove_user_access_restrictions,
    "rename_branch" => :rename_branch,
    "render" => :render,
    "render_raw" => :render_raw,
    "replace_all_topics" => :replace_all_topics,
    "repo_machines_for_authenticated_user" => :repo_machines_for_authenticated_user,
    "repos" => :repos,
    "repository_access_for_org" => :repository_access_for_org,
    "reprioritize_sub_issue" => :reprioritize_sub_issue,
    "request_pages_build" => :request_pages_build,
    "request_reviewers" => :request_reviewers,
    "rerequest_run" => :rerequest_run,
    "rerequest_suite" => :rerequest_suite,
    "reset_token" => :reset_token,
    "restore_package_for_authenticated_user" => :restore_package_for_authenticated_user,
    "restore_package_for_org" => :restore_package_for_org,
    "restore_package_for_user" => :restore_package_for_user,
    "restore_package_version_for_authenticated_user" =>
      :restore_package_version_for_authenticated_user,
    "restore_package_version_for_org" => :restore_package_version_for_org,
    "restore_package_version_for_user" => :restore_package_version_for_user,
    "review_custom_gates_for_run" => :review_custom_gates_for_run,
    "review_pat_grant_request" => :review_pat_grant_request,
    "review_pat_grant_requests_in_bulk" => :review_pat_grant_requests_in_bulk,
    "review_pending_deployments_for_run" => :review_pending_deployments_for_run,
    "revoke" => :revoke,
    "revoke_all_org_roles_team" => :revoke_all_org_roles_team,
    "revoke_all_org_roles_user" => :revoke_all_org_roles_user,
    "revoke_installation_access_token" => :revoke_installation_access_token,
    "revoke_org_role_team" => :revoke_org_role_team,
    "revoke_org_role_user" => :revoke_org_role_user,
    "root" => :root,
    "scope_token" => :scope_token,
    "set_actions_cache_retention_limit_for_enterprise" =>
      :set_actions_cache_retention_limit_for_enterprise,
    "set_actions_cache_retention_limit_for_organization" =>
      :set_actions_cache_retention_limit_for_organization,
    "set_actions_cache_retention_limit_for_repository" =>
      :set_actions_cache_retention_limit_for_repository,
    "set_actions_cache_storage_limit_for_enterprise" =>
      :set_actions_cache_storage_limit_for_enterprise,
    "set_actions_cache_storage_limit_for_organization" =>
      :set_actions_cache_storage_limit_for_organization,
    "set_actions_cache_storage_limit_for_repository" =>
      :set_actions_cache_storage_limit_for_repository,
    "set_admin_branch_protection" => :set_admin_branch_protection,
    "set_allowed_actions_organization" => :set_allowed_actions_organization,
    "set_allowed_actions_repository" => :set_allowed_actions_repository,
    "set_app_access_restrictions" => :set_app_access_restrictions,
    "set_artifact_and_log_retention_settings_organization" =>
      :set_artifact_and_log_retention_settings_organization,
    "set_artifact_and_log_retention_settings_repository" =>
      :set_artifact_and_log_retention_settings_repository,
    "set_cluster_deployment_records" => :set_cluster_deployment_records,
    "set_codespaces_access" => :set_codespaces_access,
    "set_codespaces_access_users" => :set_codespaces_access_users,
    "set_configuration_as_default" => :set_configuration_as_default,
    "set_configuration_as_default_for_enterprise" => :set_configuration_as_default_for_enterprise,
    "set_copilot_content_exclusion_for_organization" =>
      :set_copilot_content_exclusion_for_organization,
    "set_custom_labels_for_self_hosted_runner_for_org" =>
      :set_custom_labels_for_self_hosted_runner_for_org,
    "set_custom_labels_for_self_hosted_runner_for_repo" =>
      :set_custom_labels_for_self_hosted_runner_for_repo,
    "set_custom_oidc_sub_claim_for_repo" => :set_custom_oidc_sub_claim_for_repo,
    "set_fork_pr_contributor_approval_permissions_organization" =>
      :set_fork_pr_contributor_approval_permissions_organization,
    "set_fork_pr_contributor_approval_permissions_repository" =>
      :set_fork_pr_contributor_approval_permissions_repository,
    "set_github_actions_default_workflow_permissions_organization" =>
      :set_github_actions_default_workflow_permissions_organization,
    "set_github_actions_default_workflow_permissions_repository" =>
      :set_github_actions_default_workflow_permissions_repository,
    "set_github_actions_permissions_organization" => :set_github_actions_permissions_organization,
    "set_github_actions_permissions_repository" => :set_github_actions_permissions_repository,
    "set_immutable_releases_settings" => :set_immutable_releases_settings,
    "set_immutable_releases_settings_repositories" =>
      :set_immutable_releases_settings_repositories,
    "set_issue_field_values" => :set_issue_field_values,
    "set_labels" => :set_labels,
    "set_lfs_preference" => :set_lfs_preference,
    "set_membership_for_user" => :set_membership_for_user,
    "set_primary_email_visibility_for_authenticated_user" =>
      :set_primary_email_visibility_for_authenticated_user,
    "set_private_repo_fork_pr_workflows_settings_organization" =>
      :set_private_repo_fork_pr_workflows_settings_organization,
    "set_private_repo_fork_pr_workflows_settings_repository" =>
      :set_private_repo_fork_pr_workflows_settings_repository,
    "set_public_membership_for_authenticated_user" =>
      :set_public_membership_for_authenticated_user,
    "set_repo_access_to_self_hosted_runner_group_in_org" =>
      :set_repo_access_to_self_hosted_runner_group_in_org,
    "set_repo_subscription" => :set_repo_subscription,
    "set_repositories_for_secret_for_authenticated_user" =>
      :set_repositories_for_secret_for_authenticated_user,
    "set_repository_access_default_level" => :set_repository_access_default_level,
    "set_restrictions_for_authenticated_user" => :set_restrictions_for_authenticated_user,
    "set_restrictions_for_org" => :set_restrictions_for_org,
    "set_restrictions_for_repo" => :set_restrictions_for_repo,
    "set_selected_repos_for_org_secret" => :set_selected_repos_for_org_secret,
    "set_selected_repos_for_org_variable" => :set_selected_repos_for_org_variable,
    "set_selected_repositories_enabled_github_actions_organization" =>
      :set_selected_repositories_enabled_github_actions_organization,
    "set_selected_repositories_self_hosted_runners_organization" =>
      :set_selected_repositories_self_hosted_runners_organization,
    "set_self_hosted_runners_in_group_for_org" => :set_self_hosted_runners_in_group_for_org,
    "set_self_hosted_runners_permissions_organization" =>
      :set_self_hosted_runners_permissions_organization,
    "set_status_check_contexts" => :set_status_check_contexts,
    "set_suites_preferences" => :set_suites_preferences,
    "set_team_access_restrictions" => :set_team_access_restrictions,
    "set_thread_subscription" => :set_thread_subscription,
    "set_user_access_restrictions" => :set_user_access_restrictions,
    "set_workflow_access_to_repository" => :set_workflow_access_to_repository,
    "star" => :star,
    "star_repo_for_authenticated_user" => :star_repo_for_authenticated_user,
    "start_for_authenticated_user" => :start_for_authenticated_user,
    "start_for_org" => :start_for_org,
    "start_import" => :start_import,
    "stop_for_authenticated_user" => :stop_for_authenticated_user,
    "stop_in_organization" => :stop_in_organization,
    "submit_review" => :submit_review,
    "suspend_installation" => :suspend_installation,
    "test_push_webhook" => :test_push_webhook,
    "topics" => :topics,
    "transfer" => :transfer,
    "unblock" => :unblock,
    "unblock_user" => :unblock_user,
    "unfollow" => :unfollow,
    "unlock" => :unlock,
    "unlock_repo_for_authenticated_user" => :unlock_repo_for_authenticated_user,
    "unlock_repo_for_org" => :unlock_repo_for_org,
    "unpin_comment" => :unpin_comment,
    "unstar" => :unstar,
    "unstar_repo_for_authenticated_user" => :unstar_repo_for_authenticated_user,
    "unsuspend_installation" => :unsuspend_installation,
    "update" => :update,
    "update_alert" => :update_alert,
    "update_authenticated" => :update_authenticated,
    "update_branch" => :update_branch,
    "update_branch_protection" => :update_branch_protection,
    "update_budget_org" => :update_budget_org,
    "update_campaign" => :update_campaign,
    "update_comment" => :update_comment,
    "update_commit_comment" => :update_commit_comment,
    "update_configuration" => :update_configuration,
    "update_default_setup" => :update_default_setup,
    "update_deployment_branch_policy" => :update_deployment_branch_policy,
    "update_enterprise_configuration" => :update_enterprise_configuration,
    "update_environment_variable" => :update_environment_variable,
    "update_for_authenticated_user" => :update_for_authenticated_user,
    "update_hosted_runner_for_org" => :update_hosted_runner_for_org,
    "update_import" => :update_import,
    "update_in_org" => :update_in_org,
    "update_information_about_pages_site" => :update_information_about_pages_site,
    "update_invitation" => :update_invitation,
    "update_issue_field" => :update_issue_field,
    "update_issue_type" => :update_issue_type,
    "update_item_for_org" => :update_item_for_org,
    "update_item_for_user" => :update_item_for_user,
    "update_label" => :update_label,
    "update_legacy" => :update_legacy,
    "update_membership_for_authenticated_user" => :update_membership_for_authenticated_user,
    "update_milestone" => :update_milestone,
    "update_network_configuration_for_org" => :update_network_configuration_for_org,
    "update_oidc_custom_sub_template_for_org" => :update_oidc_custom_sub_template_for_org,
    "update_org_pattern_configs" => :update_org_pattern_configs,
    "update_org_private_registry" => :update_org_private_registry,
    "update_org_ruleset" => :update_org_ruleset,
    "update_org_variable" => :update_org_variable,
    "update_pat_access" => :update_pat_access,
    "update_pat_accesses" => :update_pat_accesses,
    "update_pull_request_review_protection" => :update_pull_request_review_protection,
    "update_ref" => :update_ref,
    "update_release" => :update_release,
    "update_release_asset" => :update_release_asset,
    "update_repo_ruleset" => :update_repo_ruleset,
    "update_repo_variable" => :update_repo_variable,
    "update_repository_access_for_org" => :update_repository_access_for_org,
    "update_repository_advisory" => :update_repository_advisory,
    "update_review" => :update_review,
    "update_review_comment" => :update_review_comment,
    "update_self_hosted_runner_group_for_org" => :update_self_hosted_runner_group_for_org,
    "update_status_check_protection" => :update_status_check_protection,
    "update_webhook" => :update_webhook,
    "update_webhook_config_for_app" => :update_webhook_config_for_app,
    "update_webhook_config_for_org" => :update_webhook_config_for_org,
    "update_webhook_config_for_repo" => :update_webhook_config_for_repo,
    "upload_release_asset" => :upload_release_asset,
    "upload_sarif" => :upload_sarif,
    "users" => :users
  }

  @parameters %{
    "account_id" => :account_id,
    "activity_type" => :activity_type,
    "actor" => :actor,
    "actor_id" => :actor_id,
    "actor_name" => :actor_name,
    "actor_name_substring" => :actor_name_substring,
    "actor_type" => :actor_type,
    "advanced_search" => :advanced_search,
    "affects" => :affects,
    "affiliation" => :affiliation,
    "after" => :after,
    "alert_number" => :alert_number,
    "all" => :all,
    "analysis_id" => :analysis_id,
    "anon" => :anon,
    "api_route_substring" => :api_route_substring,
    "app_id" => :app_id,
    "app_slug" => :app_slug,
    "archive_format" => :archive_format,
    "artifact_id" => :artifact_id,
    "artifact_registry" => :artifact_registry,
    "artifact_registry_url" => :artifact_registry_url,
    "asset_id" => :asset_id,
    "assignee" => :assignee,
    "assignees" => :assignees,
    "assignment_id" => :assignment_id,
    "attempt_number" => :attempt_number,
    "attestation_id" => :attestation_id,
    "author" => :author,
    "author_id" => :author_id,
    "autolink_id" => :autolink_id,
    "base" => :base,
    "basehead" => :basehead,
    "before" => :before,
    "branch" => :branch,
    "branch_policy_id" => :branch_policy_id,
    "budget_id" => :budget_id,
    "build_id" => :build_id,
    "cache_id" => :cache_id,
    "campaign_number" => :campaign_number,
    "check_name" => :check_name,
    "check_run_id" => :check_run_id,
    "check_suite_id" => :check_suite_id,
    "classroom_id" => :classroom_id,
    "client_id" => :client_id,
    "client_ip" => :client_ip,
    "cluster" => :cluster,
    "code" => :code,
    "codeql_variant_analysis_id" => :codeql_variant_analysis_id,
    "codespace_name" => :codespace_name,
    "collab" => :collab,
    "comment_id" => :comment_id,
    "commit_sha" => :commit_sha,
    "committer" => :committer,
    "configuration_id" => :configuration_id,
    "confirm_delete" => :confirm_delete,
    "content" => :content,
    "created" => :created,
    "creator" => :creator,
    "cursor" => :cursor,
    "custom_property_name" => :custom_property_name,
    "cve_id" => :cve_id,
    "cwes" => :cwes,
    "day" => :day,
    "delivery_id" => :delivery_id,
    "deployment_id" => :deployment_id,
    "devcontainer_path" => :devcontainer_path,
    "dir" => :dir,
    "direction" => :direction,
    "ecosystem" => :ecosystem,
    "enablement" => :enablement,
    "enterprise" => :enterprise,
    "enterprise_team" => :enterprise_team,
    "environment" => :environment,
    "environment_name" => :environment_name,
    "epss_percentage" => :epss_percentage,
    "epss_percentile" => :epss_percentile,
    "event" => :event,
    "event_id" => :event_id,
    "exclude" => :exclude,
    "exclude_pull_requests" => :exclude_pull_requests,
    "export_id" => :export_id,
    "featured" => :featured,
    "field_id" => :field_id,
    "fields" => :fields,
    "file_sha" => :file_sha,
    "filter" => :filter,
    "ghsa_id" => :ghsa_id,
    "gist_id" => :gist_id,
    "gpg_key_id" => :gpg_key_id,
    "has" => :has,
    "head" => :head,
    "head_sha" => :head_sha,
    "hide_secret" => :hide_secret,
    "hook_id" => :hook_id,
    "hosted_runner_id" => :hosted_runner_id,
    "image_definition_id" => :image_definition_id,
    "includes_parents" => :includes_parents,
    "installation_id" => :installation_id,
    "invitation_id" => :invitation_id,
    "invitation_source" => :invitation_source,
    "is_multi_repo" => :is_multi_repo,
    "is_publicly_leaked" => :is_publicly_leaked,
    "is_withdrawn" => :is_withdrawn,
    "issue_field_id" => :issue_field_id,
    "issue_id" => :issue_id,
    "issue_number" => :issue_number,
    "issue_type_id" => :issue_type_id,
    "item_id" => :item_id,
    "job_id" => :job_id,
    "key" => :key,
    "key_id" => :key_id,
    "label" => :label,
    "labels" => :labels,
    "language" => :language,
    "last_used_after" => :last_used_after,
    "last_used_before" => :last_used_before,
    "license" => :license,
    "location" => :location,
    "manifest" => :manifest,
    "max_timestamp" => :max_timestamp,
    "mentioned" => :mentioned,
    "migration_id" => :migration_id,
    "milestone" => :milestone,
    "milestone_number" => :milestone_number,
    "min_timestamp" => :min_timestamp,
    "model" => :model,
    "modified" => :modified,
    "month" => :month,
    "name" => :name,
    "network_configuration_id" => :network_configuration_id,
    "network_settings_id" => :network_settings_id,
    "order" => :order,
    "org" => :org,
    "orgs" => :orgs,
    "outdated" => :outdated,
    "owned" => :owned,
    "owner" => :owner,
    "package" => :package,
    "package_name" => :package_name,
    "package_type" => :package_type,
    "package_version_id" => :package_version_id,
    "page" => :page,
    "pages_deployment_id" => :pages_deployment_id,
    "participating" => :participating,
    "pat_id" => :pat_id,
    "pat_request_id" => :pat_request_id,
    "path" => :path,
    "per" => :per,
    "per_page" => :per_page,
    "permission" => :permission,
    "plan_id" => :plan_id,
    "pr" => :pr,
    "predicate_type" => :predicate_type,
    "product" => :product,
    "project_number" => :project_number,
    "protected" => :protected,
    "protection_rule_id" => :protection_rule_id,
    "published" => :published,
    "pull_number" => :pull_number,
    "pulls" => :pulls,
    "q" => :q,
    "reaction_id" => :reaction_id,
    "recursive" => :recursive,
    "ref" => :ref,
    "release_id" => :release_id,
    "repo" => :repo,
    "repo_name" => :repo_name,
    "repo_owner" => :repo_owner,
    "repository" => :repository,
    "repository_id" => :repository_id,
    "repository_name" => :repository_name,
    "repository_query" => :repository_query,
    "resolution" => :resolution,
    "review_id" => :review_id,
    "role" => :role,
    "role_id" => :role_id,
    "rule_suite_id" => :rule_suite_id,
    "rule_suite_result" => :rule_suite_result,
    "ruleset_id" => :ruleset_id,
    "run_id" => :run_id,
    "runner_group_id" => :runner_group_id,
    "runner_id" => :runner_id,
    "runtime_risk" => :runtime_risk,
    "s" => :s,
    "sarif_id" => :sarif_id,
    "scope" => :scope,
    "secret_name" => :secret_name,
    "secret_type" => :secret_type,
    "security_product" => :security_product,
    "severity" => :severity,
    "sha" => :sha,
    "since" => :since,
    "sku" => :sku,
    "sort" => :sort,
    "ssh_signing_key_id" => :ssh_signing_key_id,
    "state" => :state,
    "status" => :status,
    "status_id" => :status_id,
    "subject_digest" => :subject_digest,
    "subject_id" => :subject_id,
    "subject_name_substring" => :subject_name_substring,
    "subject_type" => :subject_type,
    "tag" => :tag,
    "tag_sha" => :tag_sha,
    "target_type" => :target_type,
    "target_user" => :target_user,
    "targets" => :targets,
    "task" => :task,
    "team_id" => :team_id,
    "team_slug" => :team_slug,
    "team_type" => :team_type,
    "template_owner" => :template_owner,
    "template_repo" => :template_repo,
    "thread_id" => :thread_id,
    "time_period" => :time_period,
    "timestamp_increment" => :timestamp_increment,
    "token" => :token,
    "token_id" => :token_id,
    "tool_guid" => :tool_guid,
    "tool_name" => :tool_name,
    "tree_sha" => :tree_sha,
    "type" => :type,
    "until" => :until,
    "updated" => :updated,
    "user" => :user,
    "user_id" => :user_id,
    "username" => :username,
    "validity" => :validity,
    "version" => :version,
    "version_id" => :version_id,
    "view_number" => :view_number,
    "visibility" => :visibility,
    "visible_to_repository" => :visible_to_repository,
    "workflow_id" => :workflow_id,
    "year" => :year
  }

  @spec method!(String.t()) :: atom()
  def method!(method), do: fetch!(@methods, method, :method)

  @spec module!(String.t()) :: module()
  def module!(module_name), do: fetch!(@modules, module_name, :module)

  @spec module_by_name!(String.t()) :: module()
  def module_by_name!(module_name), do: fetch!(@module_names, module_name, :module_name)

  @spec generated_modules() :: [module()]
  def generated_modules, do: @modules |> Map.values() |> Enum.sort()

  @spec event_segment!(module()) :: atom()
  def event_segment!(module), do: fetch!(@module_event_segments, module, :event_segment)

  @spec function!(String.t()) :: atom()
  def function!(name), do: fetch!(@functions, name, :function)

  @spec parameter!(String.t()) :: atom()
  def parameter!(name), do: fetch!(@parameters, name, :parameter)

  defp fetch!(registry, key, kind) do
    case Map.fetch(registry, key) do
      {:ok, value} -> value
      :error -> raise ArgumentError, "unknown GitHubEx #{kind} atom registry key: #{inspect(key)}"
    end
  end
end
